project_id = "ivmnpukucidiclxcbugp"

[functions.send-email]
verify_jwt = false

[functions.portal-me]
verify_jwt = true

[functions.portal-jobs]
verify_jwt = true

[functions.portal-appointments]
verify_jwt = true

[functions.portal-book]
verify_jwt = true

[functions.portal-estimate]
verify_jwt = false

[functions.portal-estimate-approve]
verify_jwt = false

[functions.portal-job-complete]
verify_jwt = false

[functions.portal-maintenance-reminders]
verify_jwt = false

[functions.portal-admin-submissions]
verify_jwt = false

[functions.ai-help-chat]
verify_jwt = false

[functions.resend-status]
verify_jwt = false

[functions.sync-google-reviews]
verify_jwt = false

[functions.get-google-reviews]
verify_jwt = false

[functions.estimate]
verify_jwt = false

[functions.twilio-missed-call]
verify_jwt = false
